use crate::types::{FullAnalysis, IssueSeverity, MigrationPlan, MigrationPath, RiskRating};
use crate::report::NttConfigGenerator;

/// Generates markdown reports
pub struct MarkdownGenerator;

impl MarkdownGenerator {
    /// Generate full migration report
    pub fn generate(analysis: &FullAnalysis, plan: &MigrationPlan) -> String {
        let mut md = String::new();

        // Header
        md.push_str(&format!(
            "# Migration Report: {} ({})\n\n",
            analysis.token.name, analysis.token.symbol
        ));
        md.push_str(&format!(
            "> Generated by Daybreak - EVM to Solana Migration Tool\n\n"
        ));

        // Summary
        md.push_str("## Summary\n\n");
        md.push_str(&format!(
            "| Property | Value |\n\
             |----------|-------|\n\
             | Token | {} ({}) |\n\
             | Chain | {} |\n\
             | Address | `{}` |\n\
             | Decimals | {} |\n\
             | Risk Score | {}/100 ({}) |\n\
             | NTT Compatible | {} |\n\
             | Recommended Path | {} |\n\n",
            analysis.token.name,
            analysis.token.symbol,
            analysis.token.chain,
            analysis.token.address,
            analysis.token.decimals,
            analysis.risk_score.total,
            analysis.risk_score.rating,
            if analysis.compatibility.is_compatible { "Yes" } else { "No" },
            plan.recommended_path
        ));

        // Risk Score Details
        md.push_str("## Risk Assessment\n\n");
        md.push_str(&Self::risk_badge(&analysis.risk_score.rating));
        md.push_str("\n\n");
        md.push_str("| Component | Score | Max |\n");
        md.push_str("|-----------|-------|-----|\n");
        md.push_str(&format!(
            "| Decimal Handling | {} | 20 |\n",
            analysis.risk_score.components.decimal_handling
        ));
        md.push_str(&format!(
            "| Token Features | {} | 25 |\n",
            analysis.risk_score.components.token_features
        ));
        md.push_str(&format!(
            "| Bytecode Complexity | {} | 20 |\n",
            analysis.risk_score.components.bytecode_complexity
        ));
        md.push_str(&format!(
            "| Holder Concentration | {} | 15 |\n",
            analysis.risk_score.components.holder_concentration
        ));
        md.push_str(&format!(
            "| Bridge Status | {} | 20 |\n",
            analysis.risk_score.components.bridge_status
        ));
        md.push_str(&format!(
            "| **Total** | **{}** | **100** |\n\n",
            analysis.risk_score.total
        ));

        // Token Capabilities
        md.push_str("## Token Capabilities\n\n");
        md.push_str("| Feature | Status |\n");
        md.push_str("|---------|--------|\n");
        md.push_str(&format!(
            "| Mintable | {} |\n",
            Self::bool_emoji(analysis.capabilities.has_mint)
        ));
        md.push_str(&format!(
            "| Burnable | {} |\n",
            Self::bool_emoji(analysis.capabilities.has_burn)
        ));
        md.push_str(&format!(
            "| Pausable | {} |\n",
            Self::bool_emoji(analysis.capabilities.has_pause)
        ));
        md.push_str(&format!(
            "| Blacklist | {} |\n",
            Self::bool_emoji(analysis.capabilities.has_blacklist)
        ));
        md.push_str(&format!(
            "| Upgradeable | {} |\n\n",
            Self::bool_emoji(analysis.capabilities.is_upgradeable)
        ));

        // Bytecode Analysis
        md.push_str("## Bytecode Analysis\n\n");
        md.push_str(&format!(
            "- **Size**: {} bytes ({})\n",
            analysis.bytecode.size_bytes, analysis.bytecode.complexity
        ));
        md.push_str(&format!(
            "- **Is Proxy**: {}\n",
            if analysis.bytecode.is_proxy { "Yes" } else { "No" }
        ));
        if let Some(ref proxy_type) = analysis.bytecode.proxy_type {
            md.push_str(&format!("- **Proxy Type**: {}\n", proxy_type));
        }
        if let Some(ref impl_addr) = analysis.bytecode.implementation_address {
            md.push_str(&format!("- **Implementation**: `{}`\n", impl_addr));
        }
        if analysis.bytecode.has_selfdestruct {
            md.push_str("- **Warning**: Contains `selfdestruct` opcode\n");
        }
        if analysis.bytecode.has_fee_pattern {
            md.push_str("- **Warning**: Fee-on-transfer pattern detected\n");
        }
        md.push('\n');

        // Compatibility Issues
        if !analysis.compatibility.issues.is_empty() {
            md.push_str("## Compatibility Issues\n\n");
            for issue in &analysis.compatibility.issues {
                let icon = match issue.severity {
                    IssueSeverity::Info => "ℹ️",
                    IssueSeverity::Warning => "⚠️",
                    IssueSeverity::Error => "❌",
                };
                md.push_str(&format!("### {} {}\n\n", icon, issue.title));
                md.push_str(&format!("{}\n\n", issue.description));
                md.push_str(&format!("**Recommendation**: {}\n\n", issue.recommendation));
            }
        }

        // Migration Paths Comparison
        md.push_str("## Migration Paths\n\n");
        md.push_str(&Self::generate_comparison_table(&plan.paths));
        md.push('\n');

        // Detailed path analysis
        for path in &plan.paths {
            md.push_str(&format!("### {}\n\n", path.method));
            md.push_str(&format!("**Feasibility**: {}\n\n", path.feasibility));
            md.push_str(&format!(
                "- **Estimated Cost**: {}\n",
                path.estimated_cost_usd
            ));
            md.push_str(&format!("- **Estimated Time**: {}\n\n", path.estimated_time));

            if !path.pros.is_empty() {
                md.push_str("**Pros**:\n");
                for pro in &path.pros {
                    md.push_str(&format!("- {}\n", pro));
                }
                md.push('\n');
            }

            if !path.cons.is_empty() {
                md.push_str("**Cons**:\n");
                for con in &path.cons {
                    md.push_str(&format!("- {}\n", con));
                }
                md.push('\n');
            }
        }

        // Migration Steps (for recommended path)
        md.push_str("## Migration Steps\n\n");
        for step in &plan.steps {
            md.push_str(&format!(
                "### Step {}: {}\n\n",
                step.order, step.title
            ));
            md.push_str(&format!("{}\n\n", step.description));
            if let Some(ref cmd) = step.command {
                md.push_str(&format!("```bash\n{}\n```\n\n", cmd));
            }
        }

        // NTT CLI Commands
        md.push_str("## NTT CLI Commands\n\n");
        md.push_str("```bash\n");
        for cmd in NttConfigGenerator::generate_cli_commands(analysis) {
            md.push_str(&format!("{}\n", cmd));
        }
        md.push_str("```\n\n");

        md
    }

    fn risk_badge(rating: &RiskRating) -> String {
        match rating {
            RiskRating::Low => "![Risk: Low](https://img.shields.io/badge/Risk-Low-green)".to_string(),
            RiskRating::Medium => "![Risk: Medium](https://img.shields.io/badge/Risk-Medium-yellow)".to_string(),
            RiskRating::High => "![Risk: High](https://img.shields.io/badge/Risk-High-red)".to_string(),
        }
    }

    fn bool_emoji(value: bool) -> &'static str {
        if value { "Yes" } else { "No" }
    }

    fn generate_comparison_table(paths: &[MigrationPath]) -> String {
        let mut table = String::new();
        table.push_str("| Aspect | NTT (Sunrise) | Neon EVM | Native Rewrite |\n");
        table.push_str("|--------|---------------|----------|----------------|\n");

        // Find each path
        let ntt = paths.iter().find(|p| matches!(p.method, crate::types::MigrationMethod::NttSunrise));
        let neon = paths.iter().find(|p| matches!(p.method, crate::types::MigrationMethod::NeonEvm));
        let native = paths.iter().find(|p| matches!(p.method, crate::types::MigrationMethod::NativeRewrite));

        table.push_str(&format!(
            "| Feasibility | {} | {} | {} |\n",
            ntt.map(|p| p.feasibility.to_string()).unwrap_or_default(),
            neon.map(|p| p.feasibility.to_string()).unwrap_or_default(),
            native.map(|p| p.feasibility.to_string()).unwrap_or_default(),
        ));

        table.push_str(&format!(
            "| Cost | {} | {} | {} |\n",
            ntt.map(|p| p.estimated_cost_usd.as_str()).unwrap_or("-"),
            neon.map(|p| p.estimated_cost_usd.as_str()).unwrap_or("-"),
            native.map(|p| p.estimated_cost_usd.as_str()).unwrap_or("-"),
        ));

        table.push_str(&format!(
            "| Time | {} | {} | {} |\n",
            ntt.map(|p| p.estimated_time.as_str()).unwrap_or("-"),
            neon.map(|p| p.estimated_time.as_str()).unwrap_or("-"),
            native.map(|p| p.estimated_time.as_str()).unwrap_or("-"),
        ));

        table
    }
}
