#!/bin/bash
# NTT Deployment Commands — generated by Daybreak
# Token: AAVE (Aave Token)
# Source: ethereum | Mode: locking → burning (Solana)

set -e

# 1. Initialize project
ntt init

# 2. Add source chain (ethereum)
ntt add-chain ethereum --mode locking --token 0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9

# 3. Add destination chain (Solana)
ntt add-chain solana --mode burning --decimals 8

# 4. Deploy contracts
ntt deploy

# 5. Configure rate limits (based on ~0 daily transfers)
ntt configure-limits --daily-limit 16000

# 6. Transfer SPL mint authority to NTT manager (REQUIRED for bridging)
# Replace <NTT_MANAGER> with the address from `ntt deploy` output
spl-token authorize <SPL_MINT> mint <NTT_MANAGER>

# 7. Test transfer
ntt transfer --amount 1 --to <SOLANA_ADDRESS>